[package]
name = "volant-client"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
description = "Async client SDK for producing and consuming Volant topics"

[dependencies]
volant-core = { workspace = true }
volant-protocol = { workspace = true }
bytes = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
volant-broker = { workspace = true }
volant-storage = { workspace = true }
