{{- if .Values.authToken }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "volant.fullname" . }}-auth
  labels:
    {{- include "volant.labels" . | nindent 4 }}
type: Opaque
stringData:
  token: {{ .Values.authToken | quote }}
{{- end }}
