apiVersion: v1
kind: Service
metadata:
  name: {{ include "volant.fullname" . }}
  labels:
    {{- include "volant.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "volant.selectorLabels" . | nindent 4 }}
  ports:
    - name: broker
      port: {{ .Values.service.port }}
      targetPort: broker
    {{- if .Values.metrics.enabled }}
    - name: metrics
      port: {{ .Values.service.metricsPort }}
      targetPort: metrics
    {{- end }}
